id: AB8EF2153
title: fABA2
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 20:37:23.858166
  last_modified_at: 2022-05-27 20:37:23.858169
