id: AB8EF2153
title: fDBED
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 20:37:24.012585
  last_modified_at: 2022-05-27 20:37:24.012590
