id: AB8EF2153
title: fAA0C
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 20:37:23.855713
  last_modified_at: 2022-05-27 20:37:23.855717
