id: AB8EF2153
title: f5D2D
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 20:37:23.708538
  last_modified_at: 2022-05-27 20:37:23.708541
